version: '3.9'

services:
  concessionariamanager.web:
    image: ${DOCKER_REGISTRY-}concessionariamanagerweb
    container_name: concessionariamanager.web
    networks:
      - app_network
    build:
      context: .
      dockerfile: ConcessionariaManager.Web/Dockerfile
    depends_on:
        - sqlserver
        - redis

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_Pass123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app_network
    restart: always
    healthcheck:
        test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_strong_Pass123", "-Q", "SELECT 1"]
        interval: 10s
        timeout: 5s
        retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    
volumes:
  sql_data:
  redis_data:

networks:
  app_network:
    driver: bridge
    
